// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: usrp_protocol.proto
// Protobuf C++ Version: 6.33.4

#include "usrp_protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace usrp_proto {

inline constexpr UsrpConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        tx_channels_{},
        _tx_channels_cached_byte_size_{0},
        rx_channels_{},
        _rx_channels_cached_byte_size_{0},
        tx_rates_{},
        rx_rates_{},
        tx_freqs_{},
        rx_freqs_{},
        tx_gains_{},
        rx_gains_{},
        tx_ants_{},
        rx_ants_{},
        tx_files_{},
        rx_files_{},
        clock_source_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        time_source_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        spb_{::uint64_t{0u}},
        delay_{0},
        nsamps_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR UsrpConfig::UsrpConfig(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(UsrpConfig_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UsrpConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UsrpConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UsrpConfigDefaultTypeInternal() {}
  union {
    UsrpConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UsrpConfigDefaultTypeInternal _UsrpConfig_default_instance_;

inline constexpr Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rx_shm_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        status_{static_cast< ::usrp_proto::Status >(0)},
        num_rx_ch_{0u},
        rx_nsamps_per_ch_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR Response::Response(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Response_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResponseDefaultTypeInternal() {}
  union {
    Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResponseDefaultTypeInternal _Response_default_instance_;

inline constexpr Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        tx_shm_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        config_{nullptr},
        cmd_{static_cast< ::usrp_proto::CommandType >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Request::Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Request_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestDefaultTypeInternal() {}
  union {
    Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestDefaultTypeInternal _Request_default_instance_;
}  // namespace usrp_proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_usrp_5fprotocol_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_usrp_5fprotocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_usrp_5fprotocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_._has_bits_),
        20, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.clock_source_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.time_source_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.tx_channels_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.rx_channels_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.spb_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.delay_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.nsamps_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.tx_rates_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.rx_rates_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.tx_freqs_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.rx_freqs_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.tx_gains_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.rx_gains_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.tx_ants_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.rx_ants_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.tx_files_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::UsrpConfig, _impl_.rx_files_),
        12,
        13,
        0,
        1,
        14,
        15,
        16,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Request, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Request, _impl_.cmd_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Request, _impl_.tx_shm_name_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Request, _impl_.config_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Response, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Response, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Response, _impl_.msg_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Response, _impl_.rx_shm_name_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Response, _impl_.rx_nsamps_per_ch_),
        PROTOBUF_FIELD_OFFSET(::usrp_proto::Response, _impl_.num_rx_ch_),
        2,
        0,
        1,
        4,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::usrp_proto::UsrpConfig)},
        {37, sizeof(::usrp_proto::Request)},
        {46, sizeof(::usrp_proto::Response)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::usrp_proto::_UsrpConfig_default_instance_._instance,
    &::usrp_proto::_Request_default_instance_._instance,
    &::usrp_proto::_Response_default_instance_._instance,
};
const char descriptor_table_protodef_usrp_5fprotocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023usrp_protocol.proto\022\nusrp_proto\"\277\002\n\nUs"
    "rpConfig\022\024\n\014clock_source\030\001 \001(\t\022\023\n\013time_s"
    "ource\030\002 \001(\t\022\023\n\013tx_channels\030\003 \003(\r\022\023\n\013rx_c"
    "hannels\030\004 \003(\r\022\013\n\003spb\030\005 \001(\004\022\r\n\005delay\030\006 \001("
    "\001\022\016\n\006nsamps\030\007 \001(\004\022\020\n\010tx_rates\030\010 \003(\001\022\020\n\010r"
    "x_rates\030\t \003(\001\022\020\n\010tx_freqs\030\n \003(\001\022\020\n\010rx_fr"
    "eqs\030\013 \003(\001\022\020\n\010tx_gains\030\014 \003(\001\022\020\n\010rx_gains\030"
    "\r \003(\001\022\017\n\007tx_ants\030\016 \003(\t\022\017\n\007rx_ants\030\017 \003(\t\022"
    "\020\n\010tx_files\030\020 \003(\t\022\020\n\010rx_files\030\021 \003(\t\"l\n\007R"
    "equest\022$\n\003cmd\030\001 \001(\0162\027.usrp_proto.Command"
    "Type\022\023\n\013tx_shm_name\030\002 \001(\t\022&\n\006config\030\003 \001("
    "\0132\026.usrp_proto.UsrpConfig\"}\n\010Response\022\"\n"
    "\006status\030\001 \001(\0162\022.usrp_proto.Status\022\013\n\003msg"
    "\030\002 \001(\t\022\023\n\013rx_shm_name\030\003 \001(\t\022\030\n\020rx_nsamps"
    "_per_ch\030\004 \001(\004\022\021\n\tnum_rx_ch\030\005 \001(\r*4\n\013Comm"
    "andType\022\013\n\007UNKNOWN\020\000\022\013\n\007EXECUTE\020\001\022\013\n\007REL"
    "EASE\020\002*N\n\006Status\022\022\n\016STATUS_UNKNOWN\020\000\022\013\n\007"
    "SUCCESS\020\001\022\n\n\006FAILED\020\002\022\t\n\005ERROR\020\003\022\014\n\010RELE"
    "ASED\020\004b\006proto3"
};
static ::absl::once_flag descriptor_table_usrp_5fprotocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_usrp_5fprotocol_2eproto = {
    false,
    false,
    734,
    descriptor_table_protodef_usrp_5fprotocol_2eproto,
    "usrp_protocol.proto",
    &descriptor_table_usrp_5fprotocol_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_usrp_5fprotocol_2eproto::offsets,
    file_level_enum_descriptors_usrp_5fprotocol_2eproto,
    file_level_service_descriptors_usrp_5fprotocol_2eproto,
};
namespace usrp_proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CommandType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_usrp_5fprotocol_2eproto);
  return file_level_enum_descriptors_usrp_5fprotocol_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CommandType_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_usrp_5fprotocol_2eproto);
  return file_level_enum_descriptors_usrp_5fprotocol_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Status_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

class UsrpConfig::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<UsrpConfig>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_._has_bits_);
};

UsrpConfig::UsrpConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UsrpConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:usrp_proto.UsrpConfig)
}
PROTOBUF_NDEBUG_INLINE UsrpConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::usrp_proto::UsrpConfig& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tx_channels_{visibility, arena, from.tx_channels_},
        _tx_channels_cached_byte_size_{0},
        rx_channels_{visibility, arena, from.rx_channels_},
        _rx_channels_cached_byte_size_{0},
        tx_rates_{visibility, arena, from.tx_rates_},
        rx_rates_{visibility, arena, from.rx_rates_},
        tx_freqs_{visibility, arena, from.tx_freqs_},
        rx_freqs_{visibility, arena, from.rx_freqs_},
        tx_gains_{visibility, arena, from.tx_gains_},
        rx_gains_{visibility, arena, from.rx_gains_},
        tx_ants_{visibility, arena, from.tx_ants_},
        rx_ants_{visibility, arena, from.rx_ants_},
        tx_files_{visibility, arena, from.tx_files_},
        rx_files_{visibility, arena, from.rx_files_},
        clock_source_(arena, from.clock_source_),
        time_source_(arena, from.time_source_) {}

UsrpConfig::UsrpConfig(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const UsrpConfig& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, UsrpConfig_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UsrpConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, spb_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, spb_),
           offsetof(Impl_, nsamps_) -
               offsetof(Impl_, spb_) +
               sizeof(Impl_::nsamps_));

  // @@protoc_insertion_point(copy_constructor:usrp_proto.UsrpConfig)
}
PROTOBUF_NDEBUG_INLINE UsrpConfig::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        tx_channels_{visibility, arena},
        _tx_channels_cached_byte_size_{0},
        rx_channels_{visibility, arena},
        _rx_channels_cached_byte_size_{0},
        tx_rates_{visibility, arena},
        rx_rates_{visibility, arena},
        tx_freqs_{visibility, arena},
        rx_freqs_{visibility, arena},
        tx_gains_{visibility, arena},
        rx_gains_{visibility, arena},
        tx_ants_{visibility, arena},
        rx_ants_{visibility, arena},
        tx_files_{visibility, arena},
        rx_files_{visibility, arena},
        clock_source_(arena),
        time_source_(arena) {}

inline void UsrpConfig::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, spb_),
           0,
           offsetof(Impl_, nsamps_) -
               offsetof(Impl_, spb_) +
               sizeof(Impl_::nsamps_));
}
UsrpConfig::~UsrpConfig() {
  // @@protoc_insertion_point(destructor:usrp_proto.UsrpConfig)
  SharedDtor(*this);
}
inline void UsrpConfig::SharedDtor(MessageLite& self) {
  UsrpConfig& this_ = static_cast<UsrpConfig&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.clock_source_.Destroy();
  this_._impl_.time_source_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL UsrpConfig::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) UsrpConfig(arena);
}
constexpr auto UsrpConfig::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_channels_) +
          decltype(UsrpConfig::_impl_.tx_channels_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_channels_) +
          decltype(UsrpConfig::_impl_.rx_channels_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_rates_) +
          decltype(UsrpConfig::_impl_.tx_rates_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_rates_) +
          decltype(UsrpConfig::_impl_.rx_rates_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_freqs_) +
          decltype(UsrpConfig::_impl_.tx_freqs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_freqs_) +
          decltype(UsrpConfig::_impl_.rx_freqs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_gains_) +
          decltype(UsrpConfig::_impl_.tx_gains_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_gains_) +
          decltype(UsrpConfig::_impl_.rx_gains_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_ants_) +
          decltype(UsrpConfig::_impl_.tx_ants_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_ants_) +
          decltype(UsrpConfig::_impl_.rx_ants_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_files_) +
          decltype(UsrpConfig::_impl_.tx_files_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_files_) +
          decltype(UsrpConfig::_impl_.rx_files_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(UsrpConfig), alignof(UsrpConfig), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&UsrpConfig::PlacementNew_,
                                 sizeof(UsrpConfig),
                                 alignof(UsrpConfig));
  }
}
constexpr auto UsrpConfig::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_UsrpConfig_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &UsrpConfig::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<UsrpConfig>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &UsrpConfig::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<UsrpConfig>(), &UsrpConfig::ByteSizeLong,
              &UsrpConfig::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_._cached_size_),
          false,
      },
      &UsrpConfig::kDescriptorMethods,
      &descriptor_table_usrp_5fprotocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull UsrpConfig_class_data_ =
        UsrpConfig::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
UsrpConfig::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&UsrpConfig_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(UsrpConfig_class_data_.tc_table);
  return UsrpConfig_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 17, 0, 99, 2>
UsrpConfig::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_._has_bits_),
    0, // no _extensions_
    17, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294836224,  // skipmap
    offsetof(decltype(_table_), field_entries),
    17,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    UsrpConfig_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::usrp_proto::UsrpConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string clock_source = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 12, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.clock_source_)}},
    // string time_source = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 13, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.time_source_)}},
    // repeated uint32 tx_channels = 3;
    {::_pbi::TcParser::FastV32P1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_channels_)}},
    // repeated uint32 rx_channels = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_channels_)}},
    // uint64 spb = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UsrpConfig, _impl_.spb_), 14>(),
     {40, 14, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.spb_)}},
    // double delay = 6;
    {::_pbi::TcParser::FastF64S1,
     {49, 15, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.delay_)}},
    // uint64 nsamps = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(UsrpConfig, _impl_.nsamps_), 16>(),
     {56, 16, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.nsamps_)}},
    // repeated double tx_rates = 8;
    {::_pbi::TcParser::FastF64P1,
     {66, 2, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_rates_)}},
    // repeated double rx_rates = 9;
    {::_pbi::TcParser::FastF64P1,
     {74, 3, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_rates_)}},
    // repeated double tx_freqs = 10;
    {::_pbi::TcParser::FastF64P1,
     {82, 4, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_freqs_)}},
    // repeated double rx_freqs = 11;
    {::_pbi::TcParser::FastF64P1,
     {90, 5, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_freqs_)}},
    // repeated double tx_gains = 12;
    {::_pbi::TcParser::FastF64P1,
     {98, 6, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_gains_)}},
    // repeated double rx_gains = 13;
    {::_pbi::TcParser::FastF64P1,
     {106, 7, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_gains_)}},
    // repeated string tx_ants = 14;
    {::_pbi::TcParser::FastUR1,
     {114, 8, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_ants_)}},
    // repeated string rx_ants = 15;
    {::_pbi::TcParser::FastUR1,
     {122, 9, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_ants_)}},
    // repeated string tx_files = 16;
    {::_pbi::TcParser::FastUR2,
     {386, 10, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_files_)}},
    // repeated string rx_files = 17;
    {::_pbi::TcParser::FastUR2,
     {394, 11, 0,
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_files_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string clock_source = 1;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.clock_source_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string time_source = 2;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.time_source_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated uint32 tx_channels = 3;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_channels_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // repeated uint32 rx_channels = 4;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_channels_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // uint64 spb = 5;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.spb_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // double delay = 6;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.delay_), _Internal::kHasBitsOffset + 15, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // uint64 nsamps = 7;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.nsamps_), _Internal::kHasBitsOffset + 16, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // repeated double tx_rates = 8;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_rates_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double rx_rates = 9;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_rates_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double tx_freqs = 10;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_freqs_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double rx_freqs = 11;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_freqs_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double tx_gains = 12;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_gains_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated double rx_gains = 13;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_gains_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedDouble)},
    // repeated string tx_ants = 14;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_ants_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string rx_ants = 15;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_ants_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string tx_files = 16;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.tx_files_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // repeated string rx_files = 17;
    {PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.rx_files_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\25\14\13\0\0\0\0\0\0\0\0\0\0\0\7\7\10\10\0\0\0\0\0\0"
    "usrp_proto.UsrpConfig"
    "clock_source"
    "time_source"
    "tx_ants"
    "rx_ants"
    "tx_files"
    "rx_files"
  }},
};
PROTOBUF_NOINLINE void UsrpConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:usrp_proto.UsrpConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.tx_channels_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.rx_channels_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.tx_rates_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      _impl_.rx_rates_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      _impl_.tx_freqs_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      _impl_.rx_freqs_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      _impl_.tx_gains_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
      _impl_.rx_gains_.Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00003f00U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000100U)) {
      _impl_.tx_ants_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000200U)) {
      _impl_.rx_ants_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000400U)) {
      _impl_.tx_files_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000800U)) {
      _impl_.rx_files_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      _impl_.clock_source_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      _impl_.time_source_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000c000U)) {
    ::memset(&_impl_.spb_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.delay_) -
        reinterpret_cast<char*>(&_impl_.spb_)) + sizeof(_impl_.delay_));
  }
  _impl_.nsamps_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL UsrpConfig::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const UsrpConfig& this_ = static_cast<const UsrpConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL UsrpConfig::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const UsrpConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:usrp_proto.UsrpConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string clock_source = 1;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    if (!this_._internal_clock_source().empty()) {
      const ::std::string& _s = this_._internal_clock_source();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.UsrpConfig.clock_source");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // string time_source = 2;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    if (!this_._internal_time_source().empty()) {
      const ::std::string& _s = this_._internal_time_source();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.UsrpConfig.time_source");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // repeated uint32 tx_channels = 3;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._tx_channels_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            3, this_._internal_tx_channels(), byte_size, target);
      }
    }
  }

  // repeated uint32 rx_channels = 4;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    {
      int byte_size = this_._impl_._rx_channels_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            4, this_._internal_rx_channels(), byte_size, target);
      }
    }
  }

  // uint64 spb = 5;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    if (this_._internal_spb() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          5, this_._internal_spb(), target);
    }
  }

  // double delay = 6;
  if (CheckHasBit(cached_has_bits, 0x00008000U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_delay()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          6, this_._internal_delay(), target);
    }
  }

  // uint64 nsamps = 7;
  if (CheckHasBit(cached_has_bits, 0x00010000U)) {
    if (this_._internal_nsamps() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          7, this_._internal_nsamps(), target);
    }
  }

  // repeated double tx_rates = 8;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    if (this_._internal_tx_rates_size() > 0) {
      target = stream->WriteFixedPacked(8, this_._internal_tx_rates(), target);
    }
  }

  // repeated double rx_rates = 9;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
    if (this_._internal_rx_rates_size() > 0) {
      target = stream->WriteFixedPacked(9, this_._internal_rx_rates(), target);
    }
  }

  // repeated double tx_freqs = 10;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
    if (this_._internal_tx_freqs_size() > 0) {
      target = stream->WriteFixedPacked(10, this_._internal_tx_freqs(), target);
    }
  }

  // repeated double rx_freqs = 11;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
    if (this_._internal_rx_freqs_size() > 0) {
      target = stream->WriteFixedPacked(11, this_._internal_rx_freqs(), target);
    }
  }

  // repeated double tx_gains = 12;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
    if (this_._internal_tx_gains_size() > 0) {
      target = stream->WriteFixedPacked(12, this_._internal_tx_gains(), target);
    }
  }

  // repeated double rx_gains = 13;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
    if (this_._internal_rx_gains_size() > 0) {
      target = stream->WriteFixedPacked(13, this_._internal_rx_gains(), target);
    }
  }

  // repeated string tx_ants = 14;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000100U)) {
    for (int i = 0, n = this_._internal_tx_ants_size(); i < n; ++i) {
      const auto& s = this_._internal_tx_ants().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.UsrpConfig.tx_ants");
      target = stream->WriteString(14, s, target);
    }
  }

  // repeated string rx_ants = 15;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000200U)) {
    for (int i = 0, n = this_._internal_rx_ants_size(); i < n; ++i) {
      const auto& s = this_._internal_rx_ants().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.UsrpConfig.rx_ants");
      target = stream->WriteString(15, s, target);
    }
  }

  // repeated string tx_files = 16;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000400U)) {
    for (int i = 0, n = this_._internal_tx_files_size(); i < n; ++i) {
      const auto& s = this_._internal_tx_files().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.UsrpConfig.tx_files");
      target = stream->WriteString(16, s, target);
    }
  }

  // repeated string rx_files = 17;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000800U)) {
    for (int i = 0, n = this_._internal_rx_files_size(); i < n; ++i) {
      const auto& s = this_._internal_rx_files().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.UsrpConfig.rx_files");
      target = stream->WriteString(17, s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:usrp_proto.UsrpConfig)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t UsrpConfig::ByteSizeLong(const MessageLite& base) {
  const UsrpConfig& this_ = static_cast<const UsrpConfig&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t UsrpConfig::ByteSizeLong() const {
  const UsrpConfig& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:usrp_proto.UsrpConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated uint32 tx_channels = 3;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_tx_channels(), 1,
              this_._impl_._tx_channels_cached_byte_size_);
    }
    // repeated uint32 rx_channels = 4;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_rx_channels(), 1,
              this_._impl_._rx_channels_cached_byte_size_);
    }
    // repeated double tx_rates = 8;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_tx_rates_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double rx_rates = 9;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_rx_rates_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double tx_freqs = 10;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_tx_freqs_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double rx_freqs = 11;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_rx_freqs_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double tx_gains = 12;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_tx_gains_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
    // repeated double rx_gains = 13;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
      ::size_t data_size = ::size_t{8} *
          ::_pbi::FromIntSize(this_._internal_rx_gains_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    // repeated string tx_ants = 14;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000100U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_tx_ants().size());
      for (int i = 0, n = this_._internal_tx_ants().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_tx_ants().Get(i));
      }
    }
    // repeated string rx_ants = 15;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000200U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_rx_ants().size());
      for (int i = 0, n = this_._internal_rx_ants().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_rx_ants().Get(i));
      }
    }
    // repeated string tx_files = 16;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000400U)) {
      total_size +=
          2 * ::google::protobuf::internal::FromIntSize(this_._internal_tx_files().size());
      for (int i = 0, n = this_._internal_tx_files().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_tx_files().Get(i));
      }
    }
    // repeated string rx_files = 17;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000800U)) {
      total_size +=
          2 * ::google::protobuf::internal::FromIntSize(this_._internal_rx_files().size());
      for (int i = 0, n = this_._internal_rx_files().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_rx_files().Get(i));
      }
    }
    // string clock_source = 1;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (!this_._internal_clock_source().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_clock_source());
      }
    }
    // string time_source = 2;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (!this_._internal_time_source().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_time_source());
      }
    }
    // uint64 spb = 5;
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (this_._internal_spb() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_spb());
      }
    }
    // double delay = 6;
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_delay()) != 0) {
        total_size += 9;
      }
    }
  }
   {
    // uint64 nsamps = 7;
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      if (this_._internal_nsamps() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_nsamps());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void UsrpConfig::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<UsrpConfig*>(&to_msg);
  auto& from = static_cast<const UsrpConfig&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:usrp_proto.UsrpConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_tx_channels()->MergeFrom(from._internal_tx_channels());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_rx_channels()->MergeFrom(from._internal_rx_channels());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_tx_rates()->MergeFrom(from._internal_tx_rates());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      _this->_internal_mutable_rx_rates()->MergeFrom(from._internal_rx_rates());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000010U)) {
      _this->_internal_mutable_tx_freqs()->MergeFrom(from._internal_tx_freqs());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000020U)) {
      _this->_internal_mutable_rx_freqs()->MergeFrom(from._internal_rx_freqs());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000040U)) {
      _this->_internal_mutable_tx_gains()->MergeFrom(from._internal_tx_gains());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000080U)) {
      _this->_internal_mutable_rx_gains()->MergeFrom(from._internal_rx_gains());
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000100U)) {
      _this->_internal_mutable_tx_ants()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_tx_ants());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000200U)) {
      _this->_internal_mutable_rx_ants()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_rx_ants());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000400U)) {
      _this->_internal_mutable_tx_files()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_tx_files());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000800U)) {
      _this->_internal_mutable_rx_files()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_rx_files());
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (!from._internal_clock_source().empty()) {
        _this->_internal_set_clock_source(from._internal_clock_source());
      } else {
        if (_this->_impl_.clock_source_.IsDefault()) {
          _this->_internal_set_clock_source("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (!from._internal_time_source().empty()) {
        _this->_internal_set_time_source(from._internal_time_source());
      } else {
        if (_this->_impl_.time_source_.IsDefault()) {
          _this->_internal_set_time_source("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (from._internal_spb() != 0) {
        _this->_impl_.spb_ = from._impl_.spb_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_delay()) != 0) {
        _this->_impl_.delay_ = from._impl_.delay_;
      }
    }
  }
  if (CheckHasBit(cached_has_bits, 0x00010000U)) {
    if (from._internal_nsamps() != 0) {
      _this->_impl_.nsamps_ = from._impl_.nsamps_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void UsrpConfig::CopyFrom(const UsrpConfig& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:usrp_proto.UsrpConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UsrpConfig::InternalSwap(UsrpConfig* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.tx_channels_.InternalSwap(&other->_impl_.tx_channels_);
  _impl_.rx_channels_.InternalSwap(&other->_impl_.rx_channels_);
  _impl_.tx_rates_.InternalSwap(&other->_impl_.tx_rates_);
  _impl_.rx_rates_.InternalSwap(&other->_impl_.rx_rates_);
  _impl_.tx_freqs_.InternalSwap(&other->_impl_.tx_freqs_);
  _impl_.rx_freqs_.InternalSwap(&other->_impl_.rx_freqs_);
  _impl_.tx_gains_.InternalSwap(&other->_impl_.tx_gains_);
  _impl_.rx_gains_.InternalSwap(&other->_impl_.rx_gains_);
  _impl_.tx_ants_.InternalSwap(&other->_impl_.tx_ants_);
  _impl_.rx_ants_.InternalSwap(&other->_impl_.rx_ants_);
  _impl_.tx_files_.InternalSwap(&other->_impl_.tx_files_);
  _impl_.rx_files_.InternalSwap(&other->_impl_.rx_files_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clock_source_, &other->_impl_.clock_source_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.time_source_, &other->_impl_.time_source_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.nsamps_)
      + sizeof(UsrpConfig::_impl_.nsamps_)
      - PROTOBUF_FIELD_OFFSET(UsrpConfig, _impl_.spb_)>(
          reinterpret_cast<char*>(&_impl_.spb_),
          reinterpret_cast<char*>(&other->_impl_.spb_));
}

::google::protobuf::Metadata UsrpConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Request::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Request>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Request, _impl_._has_bits_);
};

Request::Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Request_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:usrp_proto.Request)
}
PROTOBUF_NDEBUG_INLINE Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::usrp_proto::Request& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        tx_shm_name_(arena, from.tx_shm_name_) {}

Request::Request(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Request_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.config_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_)
                : nullptr;
  _impl_.cmd_ = from._impl_.cmd_;

  // @@protoc_insertion_point(copy_constructor:usrp_proto.Request)
}
PROTOBUF_NDEBUG_INLINE Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        tx_shm_name_(arena) {}

inline void Request::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, config_),
           0,
           offsetof(Impl_, cmd_) -
               offsetof(Impl_, config_) +
               sizeof(Impl_::cmd_));
}
Request::~Request() {
  // @@protoc_insertion_point(destructor:usrp_proto.Request)
  SharedDtor(*this);
}
inline void Request::SharedDtor(MessageLite& self) {
  Request& this_ = static_cast<Request&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.tx_shm_name_.Destroy();
  delete this_._impl_.config_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Request::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Request(arena);
}
constexpr auto Request::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Request),
                                            alignof(Request));
}
constexpr auto Request::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Request_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Request::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Request::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Request>(), &Request::ByteSizeLong,
              &Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Request, _impl_._cached_size_),
          false,
      },
      &Request::kDescriptorMethods,
      &descriptor_table_usrp_5fprotocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Request_class_data_ =
        Request::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Request_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Request_class_data_.tc_table);
  return Request_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 38, 2>
Request::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Request, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Request_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::usrp_proto::Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .usrp_proto.CommandType cmd = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Request, _impl_.cmd_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(Request, _impl_.cmd_)}},
    // string tx_shm_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Request, _impl_.tx_shm_name_)}},
    // .usrp_proto.UsrpConfig config = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(Request, _impl_.config_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .usrp_proto.CommandType cmd = 1;
    {PROTOBUF_FIELD_OFFSET(Request, _impl_.cmd_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string tx_shm_name = 2;
    {PROTOBUF_FIELD_OFFSET(Request, _impl_.tx_shm_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .usrp_proto.UsrpConfig config = 3;
    {PROTOBUF_FIELD_OFFSET(Request, _impl_.config_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::usrp_proto::UsrpConfig>()},
  }},
  {{
    "\22\0\13\0\0\0\0\0"
    "usrp_proto.Request"
    "tx_shm_name"
  }},
};
PROTOBUF_NOINLINE void Request::Clear() {
// @@protoc_insertion_point(message_clear_start:usrp_proto.Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.tx_shm_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.config_ != nullptr);
      _impl_.config_->Clear();
    }
  }
  _impl_.cmd_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Request::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Request& this_ = static_cast<const Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Request::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:usrp_proto.Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .usrp_proto.CommandType cmd = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_cmd() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_cmd(), target);
    }
  }

  // string tx_shm_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_tx_shm_name().empty()) {
      const ::std::string& _s = this_._internal_tx_shm_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.Request.tx_shm_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // .usrp_proto.UsrpConfig config = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.config_, this_._impl_.config_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:usrp_proto.Request)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Request::ByteSizeLong(const MessageLite& base) {
  const Request& this_ = static_cast<const Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Request::ByteSizeLong() const {
  const Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:usrp_proto.Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // string tx_shm_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_tx_shm_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_tx_shm_name());
      }
    }
    // .usrp_proto.UsrpConfig config = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.config_);
    }
    // .usrp_proto.CommandType cmd = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_cmd() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_cmd());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Request::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Request*>(&to_msg);
  auto& from = static_cast<const Request&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:usrp_proto.Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_tx_shm_name().empty()) {
        _this->_internal_set_tx_shm_name(from._internal_tx_shm_name());
      } else {
        if (_this->_impl_.tx_shm_name_.IsDefault()) {
          _this->_internal_set_tx_shm_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.config_ != nullptr);
      if (_this->_impl_.config_ == nullptr) {
        _this->_impl_.config_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.config_);
      } else {
        _this->_impl_.config_->MergeFrom(*from._impl_.config_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_cmd() != 0) {
        _this->_impl_.cmd_ = from._impl_.cmd_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Request::CopyFrom(const Request& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:usrp_proto.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Request::InternalSwap(Request* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tx_shm_name_, &other->_impl_.tx_shm_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Request, _impl_.cmd_)
      + sizeof(Request::_impl_.cmd_)
      - PROTOBUF_FIELD_OFFSET(Request, _impl_.config_)>(
          reinterpret_cast<char*>(&_impl_.config_),
          reinterpret_cast<char*>(&other->_impl_.config_));
}

::google::protobuf::Metadata Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Response::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Response, _impl_._has_bits_);
};

Response::Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Response_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:usrp_proto.Response)
}
PROTOBUF_NDEBUG_INLINE Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::usrp_proto::Response& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        msg_(arena, from.msg_),
        rx_shm_name_(arena, from.rx_shm_name_) {}

Response::Response(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Response_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, status_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, status_),
           offsetof(Impl_, rx_nsamps_per_ch_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::rx_nsamps_per_ch_));

  // @@protoc_insertion_point(copy_constructor:usrp_proto.Response)
}
PROTOBUF_NDEBUG_INLINE Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        msg_(arena),
        rx_shm_name_(arena) {}

inline void Response::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, status_),
           0,
           offsetof(Impl_, rx_nsamps_per_ch_) -
               offsetof(Impl_, status_) +
               sizeof(Impl_::rx_nsamps_per_ch_));
}
Response::~Response() {
  // @@protoc_insertion_point(destructor:usrp_proto.Response)
  SharedDtor(*this);
}
inline void Response::SharedDtor(MessageLite& self) {
  Response& this_ = static_cast<Response&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.rx_shm_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Response::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Response(arena);
}
constexpr auto Response::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Response),
                                            alignof(Response));
}
constexpr auto Response::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Response_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Response::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Response>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Response::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Response>(), &Response::ByteSizeLong,
              &Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Response, _impl_._cached_size_),
          false,
      },
      &Response::kDescriptorMethods,
      &descriptor_table_usrp_5fprotocol_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Response_class_data_ =
        Response::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Response_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Response_class_data_.tc_table);
  return Response_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 42, 2>
Response::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Response, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Response_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::usrp_proto::Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .usrp_proto.Status status = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Response, _impl_.status_), 2>(),
     {8, 2, 0,
      PROTOBUF_FIELD_OFFSET(Response, _impl_.status_)}},
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(Response, _impl_.msg_)}},
    // string rx_shm_name = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(Response, _impl_.rx_shm_name_)}},
    // uint64 rx_nsamps_per_ch = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(Response, _impl_.rx_nsamps_per_ch_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(Response, _impl_.rx_nsamps_per_ch_)}},
    // uint32 num_rx_ch = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Response, _impl_.num_rx_ch_), 3>(),
     {40, 3, 0,
      PROTOBUF_FIELD_OFFSET(Response, _impl_.num_rx_ch_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .usrp_proto.Status status = 1;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.status_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.msg_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string rx_shm_name = 3;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.rx_shm_name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 rx_nsamps_per_ch = 4;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.rx_nsamps_per_ch_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint32 num_rx_ch = 5;
    {PROTOBUF_FIELD_OFFSET(Response, _impl_.num_rx_ch_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\23\0\3\13\0\0\0\0"
    "usrp_proto.Response"
    "msg"
    "rx_shm_name"
  }},
};
PROTOBUF_NOINLINE void Response::Clear() {
// @@protoc_insertion_point(message_clear_start:usrp_proto.Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.msg_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.rx_shm_name_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001cU)) {
    ::memset(&_impl_.status_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.rx_nsamps_per_ch_) -
        reinterpret_cast<char*>(&_impl_.status_)) + sizeof(_impl_.rx_nsamps_per_ch_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Response::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Response& this_ = static_cast<const Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Response::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:usrp_proto.Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .usrp_proto.Status status = 1;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_status(), target);
    }
  }

  // string msg = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_msg().empty()) {
      const ::std::string& _s = this_._internal_msg();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.Response.msg");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string rx_shm_name = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_rx_shm_name().empty()) {
      const ::std::string& _s = this_._internal_rx_shm_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "usrp_proto.Response.rx_shm_name");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // uint64 rx_nsamps_per_ch = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_rx_nsamps_per_ch() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_rx_nsamps_per_ch(), target);
    }
  }

  // uint32 num_rx_ch = 5;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_num_rx_ch() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_num_rx_ch(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:usrp_proto.Response)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Response::ByteSizeLong(const MessageLite& base) {
  const Response& this_ = static_cast<const Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Response::ByteSizeLong() const {
  const Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:usrp_proto.Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string msg = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_msg().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_msg());
      }
    }
    // string rx_shm_name = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_rx_shm_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rx_shm_name());
      }
    }
    // .usrp_proto.Status status = 1;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
    // uint32 num_rx_ch = 5;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_num_rx_ch() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_num_rx_ch());
      }
    }
    // uint64 rx_nsamps_per_ch = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_rx_nsamps_per_ch() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_rx_nsamps_per_ch());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Response::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Response*>(&to_msg);
  auto& from = static_cast<const Response&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:usrp_proto.Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_msg().empty()) {
        _this->_internal_set_msg(from._internal_msg());
      } else {
        if (_this->_impl_.msg_.IsDefault()) {
          _this->_internal_set_msg("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_rx_shm_name().empty()) {
        _this->_internal_set_rx_shm_name(from._internal_rx_shm_name());
      } else {
        if (_this->_impl_.rx_shm_name_.IsDefault()) {
          _this->_internal_set_rx_shm_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_num_rx_ch() != 0) {
        _this->_impl_.num_rx_ch_ = from._impl_.num_rx_ch_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_rx_nsamps_per_ch() != 0) {
        _this->_impl_.rx_nsamps_per_ch_ = from._impl_.rx_nsamps_per_ch_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Response::CopyFrom(const Response& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:usrp_proto.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Response::InternalSwap(Response* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rx_shm_name_, &other->_impl_.rx_shm_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Response, _impl_.rx_nsamps_per_ch_)
      + sizeof(Response::_impl_.rx_nsamps_per_ch_)
      - PROTOBUF_FIELD_OFFSET(Response, _impl_.status_)>(
          reinterpret_cast<char*>(&_impl_.status_),
          reinterpret_cast<char*>(&other->_impl_.status_));
}

::google::protobuf::Metadata Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace usrp_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_usrp_5fprotocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
