// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: usrp_protocol.proto
// Protobuf C++ Version: 6.33.4

#ifndef usrp_5fprotocol_2eproto_2epb_2eh
#define usrp_5fprotocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_usrp_5fprotocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_usrp_5fprotocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_usrp_5fprotocol_2eproto;
}  // extern "C"
namespace usrp_proto {
enum CommandType : int;
extern const uint32_t CommandType_internal_data_[];
enum Status : int;
extern const uint32_t Status_internal_data_[];
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Request_class_data_;
class Response;
struct ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Response_class_data_;
class UsrpConfig;
struct UsrpConfigDefaultTypeInternal;
extern UsrpConfigDefaultTypeInternal _UsrpConfig_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull UsrpConfig_class_data_;
}  // namespace usrp_proto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::usrp_proto::CommandType_internal_data_>
    internal::EnumTraitsImpl::value<::usrp_proto::CommandType>;
template <>
internal::EnumTraitsT<::usrp_proto::Status_internal_data_>
    internal::EnumTraitsImpl::value<::usrp_proto::Status>;
}  // namespace protobuf
}  // namespace google

namespace usrp_proto {
enum CommandType : int {
  UNKNOWN = 0,
  EXECUTE = 1,
  RELEASE = 2,
  CommandType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CommandType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CommandType_internal_data_[];
inline constexpr CommandType CommandType_MIN =
    static_cast<CommandType>(0);
inline constexpr CommandType CommandType_MAX =
    static_cast<CommandType>(2);
inline bool CommandType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int CommandType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CommandType_descriptor();
template <typename T>
const ::std::string& CommandType_Name(T value) {
  static_assert(::std::is_same<T, CommandType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CommandType_Name().");
  return CommandType_Name(static_cast<CommandType>(value));
}
template <>
inline const ::std::string& CommandType_Name(CommandType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CommandType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool CommandType_Parse(
    ::absl::string_view name, CommandType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CommandType>(CommandType_descriptor(), name,
                                           value);
}
enum Status : int {
  STATUS_UNKNOWN = 0,
  SUCCESS = 1,
  FAILED = 2,
  ERROR = 3,
  RELEASED = 4,
  Status_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Status_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Status_internal_data_[];
inline constexpr Status Status_MIN =
    static_cast<Status>(0);
inline constexpr Status Status_MAX =
    static_cast<Status>(4);
inline bool Status_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int Status_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor();
template <typename T>
const ::std::string& Status_Name(T value) {
  static_assert(::std::is_same<T, Status>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return Status_Name(static_cast<Status>(value));
}
template <>
inline const ::std::string& Status_Name(Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Status_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool Status_Parse(
    ::absl::string_view name, Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Status>(Status_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class UsrpConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:usrp_proto.UsrpConfig) */ {
 public:
  inline UsrpConfig() : UsrpConfig(nullptr) {}
  ~UsrpConfig() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(UsrpConfig* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(UsrpConfig));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR UsrpConfig(::google::protobuf::internal::ConstantInitialized);

  inline UsrpConfig(const UsrpConfig& from) : UsrpConfig(nullptr, from) {}
  inline UsrpConfig(UsrpConfig&& from) noexcept
      : UsrpConfig(nullptr, ::std::move(from)) {}
  inline UsrpConfig& operator=(const UsrpConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline UsrpConfig& operator=(UsrpConfig&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UsrpConfig& default_instance() {
    return *reinterpret_cast<const UsrpConfig*>(
        &_UsrpConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(UsrpConfig& a, UsrpConfig& b) { a.Swap(&b); }
  inline void Swap(UsrpConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UsrpConfig* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UsrpConfig* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<UsrpConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const UsrpConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const UsrpConfig& from) { UsrpConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(UsrpConfig* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "usrp_proto.UsrpConfig"; }

  explicit UsrpConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  UsrpConfig(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const UsrpConfig& from);
  UsrpConfig(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, UsrpConfig&& from) noexcept
      : UsrpConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTxChannelsFieldNumber = 3,
    kRxChannelsFieldNumber = 4,
    kTxRatesFieldNumber = 8,
    kRxRatesFieldNumber = 9,
    kTxFreqsFieldNumber = 10,
    kRxFreqsFieldNumber = 11,
    kTxGainsFieldNumber = 12,
    kRxGainsFieldNumber = 13,
    kTxAntsFieldNumber = 14,
    kRxAntsFieldNumber = 15,
    kTxFilesFieldNumber = 16,
    kRxFilesFieldNumber = 17,
    kClockSourceFieldNumber = 1,
    kTimeSourceFieldNumber = 2,
    kSpbFieldNumber = 5,
    kDelayFieldNumber = 6,
    kNsampsFieldNumber = 7,
  };
  // repeated uint32 tx_channels = 3;
  int tx_channels_size() const;
  private:
  int _internal_tx_channels_size() const;

  public:
  void clear_tx_channels() ;
  ::uint32_t tx_channels(int index) const;
  void set_tx_channels(int index, ::uint32_t value);
  void add_tx_channels(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& tx_channels() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_tx_channels();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_tx_channels() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_tx_channels();

  public:
  // repeated uint32 rx_channels = 4;
  int rx_channels_size() const;
  private:
  int _internal_rx_channels_size() const;

  public:
  void clear_rx_channels() ;
  ::uint32_t rx_channels(int index) const;
  void set_rx_channels(int index, ::uint32_t value);
  void add_rx_channels(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& rx_channels() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_rx_channels();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_rx_channels() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_rx_channels();

  public:
  // repeated double tx_rates = 8;
  int tx_rates_size() const;
  private:
  int _internal_tx_rates_size() const;

  public:
  void clear_tx_rates() ;
  double tx_rates(int index) const;
  void set_tx_rates(int index, double value);
  void add_tx_rates(double value);
  const ::google::protobuf::RepeatedField<double>& tx_rates() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_tx_rates();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_tx_rates() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_tx_rates();

  public:
  // repeated double rx_rates = 9;
  int rx_rates_size() const;
  private:
  int _internal_rx_rates_size() const;

  public:
  void clear_rx_rates() ;
  double rx_rates(int index) const;
  void set_rx_rates(int index, double value);
  void add_rx_rates(double value);
  const ::google::protobuf::RepeatedField<double>& rx_rates() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_rx_rates();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_rx_rates() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_rx_rates();

  public:
  // repeated double tx_freqs = 10;
  int tx_freqs_size() const;
  private:
  int _internal_tx_freqs_size() const;

  public:
  void clear_tx_freqs() ;
  double tx_freqs(int index) const;
  void set_tx_freqs(int index, double value);
  void add_tx_freqs(double value);
  const ::google::protobuf::RepeatedField<double>& tx_freqs() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_tx_freqs();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_tx_freqs() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_tx_freqs();

  public:
  // repeated double rx_freqs = 11;
  int rx_freqs_size() const;
  private:
  int _internal_rx_freqs_size() const;

  public:
  void clear_rx_freqs() ;
  double rx_freqs(int index) const;
  void set_rx_freqs(int index, double value);
  void add_rx_freqs(double value);
  const ::google::protobuf::RepeatedField<double>& rx_freqs() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_rx_freqs();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_rx_freqs() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_rx_freqs();

  public:
  // repeated double tx_gains = 12;
  int tx_gains_size() const;
  private:
  int _internal_tx_gains_size() const;

  public:
  void clear_tx_gains() ;
  double tx_gains(int index) const;
  void set_tx_gains(int index, double value);
  void add_tx_gains(double value);
  const ::google::protobuf::RepeatedField<double>& tx_gains() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_tx_gains();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_tx_gains() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_tx_gains();

  public:
  // repeated double rx_gains = 13;
  int rx_gains_size() const;
  private:
  int _internal_rx_gains_size() const;

  public:
  void clear_rx_gains() ;
  double rx_gains(int index) const;
  void set_rx_gains(int index, double value);
  void add_rx_gains(double value);
  const ::google::protobuf::RepeatedField<double>& rx_gains() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_rx_gains();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_rx_gains() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_rx_gains();

  public:
  // repeated string tx_ants = 14;
  int tx_ants_size() const;
  private:
  int _internal_tx_ants_size() const;

  public:
  void clear_tx_ants() ;
  const ::std::string& tx_ants(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_tx_ants(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tx_ants(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_tx_ants();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_tx_ants(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& tx_ants() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_tx_ants();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_tx_ants() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_tx_ants();

  public:
  // repeated string rx_ants = 15;
  int rx_ants_size() const;
  private:
  int _internal_rx_ants_size() const;

  public:
  void clear_rx_ants() ;
  const ::std::string& rx_ants(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_rx_ants(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rx_ants(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_rx_ants();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_rx_ants(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& rx_ants() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_rx_ants();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_rx_ants() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_rx_ants();

  public:
  // repeated string tx_files = 16;
  int tx_files_size() const;
  private:
  int _internal_tx_files_size() const;

  public:
  void clear_tx_files() ;
  const ::std::string& tx_files(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_tx_files(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tx_files(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_tx_files();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_tx_files(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& tx_files() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_tx_files();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_tx_files() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_tx_files();

  public:
  // repeated string rx_files = 17;
  int rx_files_size() const;
  private:
  int _internal_rx_files_size() const;

  public:
  void clear_rx_files() ;
  const ::std::string& rx_files(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_rx_files(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rx_files(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_rx_files();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_rx_files(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& rx_files() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_rx_files();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_rx_files() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_rx_files();

  public:
  // string clock_source = 1;
  void clear_clock_source() ;
  const ::std::string& clock_source() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_clock_source(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_clock_source();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_clock_source();
  void set_allocated_clock_source(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_clock_source() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_clock_source(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_clock_source();

  public:
  // string time_source = 2;
  void clear_time_source() ;
  const ::std::string& time_source() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_time_source(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_time_source();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_time_source();
  void set_allocated_time_source(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_time_source() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_time_source(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_time_source();

  public:
  // uint64 spb = 5;
  void clear_spb() ;
  ::uint64_t spb() const;
  void set_spb(::uint64_t value);

  private:
  ::uint64_t _internal_spb() const;
  void _internal_set_spb(::uint64_t value);

  public:
  // double delay = 6;
  void clear_delay() ;
  double delay() const;
  void set_delay(double value);

  private:
  double _internal_delay() const;
  void _internal_set_delay(double value);

  public:
  // uint64 nsamps = 7;
  void clear_nsamps() ;
  ::uint64_t nsamps() const;
  void set_nsamps(::uint64_t value);

  private:
  ::uint64_t _internal_nsamps() const;
  void _internal_set_nsamps(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:usrp_proto.UsrpConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 17,
                                   0, 99,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const UsrpConfig& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> tx_channels_;
    ::google::protobuf::internal::CachedSize _tx_channels_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> rx_channels_;
    ::google::protobuf::internal::CachedSize _rx_channels_cached_byte_size_;
    ::google::protobuf::RepeatedField<double> tx_rates_;
    ::google::protobuf::RepeatedField<double> rx_rates_;
    ::google::protobuf::RepeatedField<double> tx_freqs_;
    ::google::protobuf::RepeatedField<double> rx_freqs_;
    ::google::protobuf::RepeatedField<double> tx_gains_;
    ::google::protobuf::RepeatedField<double> rx_gains_;
    ::google::protobuf::RepeatedPtrField<::std::string> tx_ants_;
    ::google::protobuf::RepeatedPtrField<::std::string> rx_ants_;
    ::google::protobuf::RepeatedPtrField<::std::string> tx_files_;
    ::google::protobuf::RepeatedPtrField<::std::string> rx_files_;
    ::google::protobuf::internal::ArenaStringPtr clock_source_;
    ::google::protobuf::internal::ArenaStringPtr time_source_;
    ::uint64_t spb_;
    double delay_;
    ::uint64_t nsamps_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_usrp_5fprotocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull UsrpConfig_class_data_;
// -------------------------------------------------------------------

class Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:usrp_proto.Response) */ {
 public:
  inline Response() : Response(nullptr) {}
  ~Response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Response(::google::protobuf::internal::ConstantInitialized);

  inline Response(const Response& from) : Response(nullptr, from) {}
  inline Response(Response&& from) noexcept
      : Response(nullptr, ::std::move(from)) {}
  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Response& default_instance() {
    return *reinterpret_cast<const Response*>(
        &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Response& a, Response& b) { a.Swap(&b); }
  inline void Swap(Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Response& from) { Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "usrp_proto.Response"; }

  explicit Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Response& from);
  Response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Response&& from) noexcept
      : Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgFieldNumber = 2,
    kRxShmNameFieldNumber = 3,
    kStatusFieldNumber = 1,
    kNumRxChFieldNumber = 5,
    kRxNsampsPerChFieldNumber = 4,
  };
  // string msg = 2;
  void clear_msg() ;
  const ::std::string& msg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_msg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_msg();
  void set_allocated_msg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_msg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_msg();

  public:
  // string rx_shm_name = 3;
  void clear_rx_shm_name() ;
  const ::std::string& rx_shm_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rx_shm_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rx_shm_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rx_shm_name();
  void set_allocated_rx_shm_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rx_shm_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rx_shm_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rx_shm_name();

  public:
  // .usrp_proto.Status status = 1;
  void clear_status() ;
  ::usrp_proto::Status status() const;
  void set_status(::usrp_proto::Status value);

  private:
  ::usrp_proto::Status _internal_status() const;
  void _internal_set_status(::usrp_proto::Status value);

  public:
  // uint32 num_rx_ch = 5;
  void clear_num_rx_ch() ;
  ::uint32_t num_rx_ch() const;
  void set_num_rx_ch(::uint32_t value);

  private:
  ::uint32_t _internal_num_rx_ch() const;
  void _internal_set_num_rx_ch(::uint32_t value);

  public:
  // uint64 rx_nsamps_per_ch = 4;
  void clear_rx_nsamps_per_ch() ;
  ::uint64_t rx_nsamps_per_ch() const;
  void set_rx_nsamps_per_ch(::uint64_t value);

  private:
  ::uint64_t _internal_rx_nsamps_per_ch() const;
  void _internal_set_rx_nsamps_per_ch(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:usrp_proto.Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::google::protobuf::internal::ArenaStringPtr rx_shm_name_;
    int status_;
    ::uint32_t num_rx_ch_;
    ::uint64_t rx_nsamps_per_ch_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_usrp_5fprotocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Response_class_data_;
// -------------------------------------------------------------------

class Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:usrp_proto.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Request(::google::protobuf::internal::ConstantInitialized);

  inline Request(const Request& from) : Request(nullptr, from) {}
  inline Request(Request&& from) noexcept
      : Request(nullptr, ::std::move(from)) {}
  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *reinterpret_cast<const Request*>(
        &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Request& a, Request& b) { a.Swap(&b); }
  inline void Swap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Request& from) { Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "usrp_proto.Request"; }

  explicit Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Request& from);
  Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Request&& from) noexcept
      : Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTxShmNameFieldNumber = 2,
    kConfigFieldNumber = 3,
    kCmdFieldNumber = 1,
  };
  // string tx_shm_name = 2;
  void clear_tx_shm_name() ;
  const ::std::string& tx_shm_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_tx_shm_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_tx_shm_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_tx_shm_name();
  void set_allocated_tx_shm_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_tx_shm_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_tx_shm_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_tx_shm_name();

  public:
  // .usrp_proto.UsrpConfig config = 3;
  bool has_config() const;
  void clear_config() ;
  const ::usrp_proto::UsrpConfig& config() const;
  [[nodiscard]] ::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE release_config();
  ::usrp_proto::UsrpConfig* PROTOBUF_NONNULL mutable_config();
  void set_allocated_config(::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_config(::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE value);
  ::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE unsafe_arena_release_config();

  private:
  const ::usrp_proto::UsrpConfig& _internal_config() const;
  ::usrp_proto::UsrpConfig* PROTOBUF_NONNULL _internal_mutable_config();

  public:
  // .usrp_proto.CommandType cmd = 1;
  void clear_cmd() ;
  ::usrp_proto::CommandType cmd() const;
  void set_cmd(::usrp_proto::CommandType value);

  private:
  ::usrp_proto::CommandType _internal_cmd() const;
  void _internal_set_cmd(::usrp_proto::CommandType value);

  public:
  // @@protoc_insertion_point(class_scope:usrp_proto.Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 38,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr tx_shm_name_;
    ::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE config_;
    int cmd_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_usrp_5fprotocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Request_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// UsrpConfig

// string clock_source = 1;
inline void UsrpConfig::clear_clock_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clock_source_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline const ::std::string& UsrpConfig::clock_source() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.clock_source)
  return _internal_clock_source();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UsrpConfig::set_clock_source(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  _impl_.clock_source_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.clock_source)
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::mutable_clock_source()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  ::std::string* _s = _internal_mutable_clock_source();
  // @@protoc_insertion_point(field_mutable:usrp_proto.UsrpConfig.clock_source)
  return _s;
}
inline const ::std::string& UsrpConfig::_internal_clock_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clock_source_.Get();
}
inline void UsrpConfig::_internal_set_clock_source(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clock_source_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::_internal_mutable_clock_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.clock_source_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UsrpConfig::release_clock_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usrp_proto.UsrpConfig.clock_source)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00001000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00001000U);
  auto* released = _impl_.clock_source_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.clock_source_.Set("", GetArena());
  }
  return released;
}
inline void UsrpConfig::set_allocated_clock_source(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00001000U);
  }
  _impl_.clock_source_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.clock_source_.IsDefault()) {
    _impl_.clock_source_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:usrp_proto.UsrpConfig.clock_source)
}

// string time_source = 2;
inline void UsrpConfig::clear_time_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_source_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline const ::std::string& UsrpConfig::time_source() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.time_source)
  return _internal_time_source();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void UsrpConfig::set_time_source(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  _impl_.time_source_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.time_source)
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::mutable_time_source()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  ::std::string* _s = _internal_mutable_time_source();
  // @@protoc_insertion_point(field_mutable:usrp_proto.UsrpConfig.time_source)
  return _s;
}
inline const ::std::string& UsrpConfig::_internal_time_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_source_.Get();
}
inline void UsrpConfig::_internal_set_time_source(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_source_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::_internal_mutable_time_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.time_source_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE UsrpConfig::release_time_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usrp_proto.UsrpConfig.time_source)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00002000U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00002000U);
  auto* released = _impl_.time_source_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.time_source_.Set("", GetArena());
  }
  return released;
}
inline void UsrpConfig::set_allocated_time_source(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00002000U);
  }
  _impl_.time_source_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.time_source_.IsDefault()) {
    _impl_.time_source_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:usrp_proto.UsrpConfig.time_source)
}

// repeated uint32 tx_channels = 3;
inline int UsrpConfig::_internal_tx_channels_size() const {
  return _internal_tx_channels().size();
}
inline int UsrpConfig::tx_channels_size() const {
  return _internal_tx_channels_size();
}
inline void UsrpConfig::clear_tx_channels() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_channels_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t UsrpConfig::tx_channels(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.tx_channels)
  return _internal_tx_channels().Get(index);
}
inline void UsrpConfig::set_tx_channels(int index, ::uint32_t value) {
  _internal_mutable_tx_channels()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.tx_channels)
}
inline void UsrpConfig::add_tx_channels(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_tx_channels()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.tx_channels)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& UsrpConfig::tx_channels() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.tx_channels)
  return _internal_tx_channels();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL UsrpConfig::mutable_tx_channels()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.tx_channels)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tx_channels();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
UsrpConfig::_internal_tx_channels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_channels_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_tx_channels() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tx_channels_;
}

// repeated uint32 rx_channels = 4;
inline int UsrpConfig::_internal_rx_channels_size() const {
  return _internal_rx_channels().size();
}
inline int UsrpConfig::rx_channels_size() const {
  return _internal_rx_channels_size();
}
inline void UsrpConfig::clear_rx_channels() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_channels_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t UsrpConfig::rx_channels(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.rx_channels)
  return _internal_rx_channels().Get(index);
}
inline void UsrpConfig::set_rx_channels(int index, ::uint32_t value) {
  _internal_mutable_rx_channels()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.rx_channels)
}
inline void UsrpConfig::add_rx_channels(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rx_channels()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.rx_channels)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& UsrpConfig::rx_channels() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.rx_channels)
  return _internal_rx_channels();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL UsrpConfig::mutable_rx_channels()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.rx_channels)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rx_channels();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
UsrpConfig::_internal_rx_channels() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_channels_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_rx_channels() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rx_channels_;
}

// uint64 spb = 5;
inline void UsrpConfig::clear_spb() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spb_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00004000U);
}
inline ::uint64_t UsrpConfig::spb() const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.spb)
  return _internal_spb();
}
inline void UsrpConfig::set_spb(::uint64_t value) {
  _internal_set_spb(value);
  SetHasBit(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.spb)
}
inline ::uint64_t UsrpConfig::_internal_spb() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spb_;
}
inline void UsrpConfig::_internal_set_spb(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spb_ = value;
}

// double delay = 6;
inline void UsrpConfig::clear_delay() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delay_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline double UsrpConfig::delay() const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.delay)
  return _internal_delay();
}
inline void UsrpConfig::set_delay(double value) {
  _internal_set_delay(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.delay)
}
inline double UsrpConfig::_internal_delay() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.delay_;
}
inline void UsrpConfig::_internal_set_delay(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.delay_ = value;
}

// uint64 nsamps = 7;
inline void UsrpConfig::clear_nsamps() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nsamps_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00010000U);
}
inline ::uint64_t UsrpConfig::nsamps() const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.nsamps)
  return _internal_nsamps();
}
inline void UsrpConfig::set_nsamps(::uint64_t value) {
  _internal_set_nsamps(value);
  SetHasBit(_impl_._has_bits_[0], 0x00010000U);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.nsamps)
}
inline ::uint64_t UsrpConfig::_internal_nsamps() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nsamps_;
}
inline void UsrpConfig::_internal_set_nsamps(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nsamps_ = value;
}

// repeated double tx_rates = 8;
inline int UsrpConfig::_internal_tx_rates_size() const {
  return _internal_tx_rates().size();
}
inline int UsrpConfig::tx_rates_size() const {
  return _internal_tx_rates_size();
}
inline void UsrpConfig::clear_tx_rates() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_rates_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double UsrpConfig::tx_rates(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.tx_rates)
  return _internal_tx_rates().Get(index);
}
inline void UsrpConfig::set_tx_rates(int index, double value) {
  _internal_mutable_tx_rates()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.tx_rates)
}
inline void UsrpConfig::add_tx_rates(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_tx_rates()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.tx_rates)
}
inline const ::google::protobuf::RepeatedField<double>& UsrpConfig::tx_rates() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.tx_rates)
  return _internal_tx_rates();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL UsrpConfig::mutable_tx_rates()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.tx_rates)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tx_rates();
}
inline const ::google::protobuf::RepeatedField<double>&
UsrpConfig::_internal_tx_rates() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_rates_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_tx_rates() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tx_rates_;
}

// repeated double rx_rates = 9;
inline int UsrpConfig::_internal_rx_rates_size() const {
  return _internal_rx_rates().size();
}
inline int UsrpConfig::rx_rates_size() const {
  return _internal_rx_rates_size();
}
inline void UsrpConfig::clear_rx_rates() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_rates_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double UsrpConfig::rx_rates(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.rx_rates)
  return _internal_rx_rates().Get(index);
}
inline void UsrpConfig::set_rx_rates(int index, double value) {
  _internal_mutable_rx_rates()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.rx_rates)
}
inline void UsrpConfig::add_rx_rates(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rx_rates()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.rx_rates)
}
inline const ::google::protobuf::RepeatedField<double>& UsrpConfig::rx_rates() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.rx_rates)
  return _internal_rx_rates();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL UsrpConfig::mutable_rx_rates()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.rx_rates)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rx_rates();
}
inline const ::google::protobuf::RepeatedField<double>&
UsrpConfig::_internal_rx_rates() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_rates_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_rx_rates() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rx_rates_;
}

// repeated double tx_freqs = 10;
inline int UsrpConfig::_internal_tx_freqs_size() const {
  return _internal_tx_freqs().size();
}
inline int UsrpConfig::tx_freqs_size() const {
  return _internal_tx_freqs_size();
}
inline void UsrpConfig::clear_tx_freqs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_freqs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000010U);
}
inline double UsrpConfig::tx_freqs(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.tx_freqs)
  return _internal_tx_freqs().Get(index);
}
inline void UsrpConfig::set_tx_freqs(int index, double value) {
  _internal_mutable_tx_freqs()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.tx_freqs)
}
inline void UsrpConfig::add_tx_freqs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_tx_freqs()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.tx_freqs)
}
inline const ::google::protobuf::RepeatedField<double>& UsrpConfig::tx_freqs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.tx_freqs)
  return _internal_tx_freqs();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL UsrpConfig::mutable_tx_freqs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.tx_freqs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tx_freqs();
}
inline const ::google::protobuf::RepeatedField<double>&
UsrpConfig::_internal_tx_freqs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_freqs_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_tx_freqs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tx_freqs_;
}

// repeated double rx_freqs = 11;
inline int UsrpConfig::_internal_rx_freqs_size() const {
  return _internal_rx_freqs().size();
}
inline int UsrpConfig::rx_freqs_size() const {
  return _internal_rx_freqs_size();
}
inline void UsrpConfig::clear_rx_freqs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_freqs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000020U);
}
inline double UsrpConfig::rx_freqs(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.rx_freqs)
  return _internal_rx_freqs().Get(index);
}
inline void UsrpConfig::set_rx_freqs(int index, double value) {
  _internal_mutable_rx_freqs()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.rx_freqs)
}
inline void UsrpConfig::add_rx_freqs(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rx_freqs()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.rx_freqs)
}
inline const ::google::protobuf::RepeatedField<double>& UsrpConfig::rx_freqs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.rx_freqs)
  return _internal_rx_freqs();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL UsrpConfig::mutable_rx_freqs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.rx_freqs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rx_freqs();
}
inline const ::google::protobuf::RepeatedField<double>&
UsrpConfig::_internal_rx_freqs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_freqs_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_rx_freqs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rx_freqs_;
}

// repeated double tx_gains = 12;
inline int UsrpConfig::_internal_tx_gains_size() const {
  return _internal_tx_gains().size();
}
inline int UsrpConfig::tx_gains_size() const {
  return _internal_tx_gains_size();
}
inline void UsrpConfig::clear_tx_gains() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_gains_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000040U);
}
inline double UsrpConfig::tx_gains(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.tx_gains)
  return _internal_tx_gains().Get(index);
}
inline void UsrpConfig::set_tx_gains(int index, double value) {
  _internal_mutable_tx_gains()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.tx_gains)
}
inline void UsrpConfig::add_tx_gains(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_tx_gains()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.tx_gains)
}
inline const ::google::protobuf::RepeatedField<double>& UsrpConfig::tx_gains() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.tx_gains)
  return _internal_tx_gains();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL UsrpConfig::mutable_tx_gains()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.tx_gains)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tx_gains();
}
inline const ::google::protobuf::RepeatedField<double>&
UsrpConfig::_internal_tx_gains() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_gains_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_tx_gains() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tx_gains_;
}

// repeated double rx_gains = 13;
inline int UsrpConfig::_internal_rx_gains_size() const {
  return _internal_rx_gains().size();
}
inline int UsrpConfig::rx_gains_size() const {
  return _internal_rx_gains_size();
}
inline void UsrpConfig::clear_rx_gains() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_gains_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000080U);
}
inline double UsrpConfig::rx_gains(int index) const {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.rx_gains)
  return _internal_rx_gains().Get(index);
}
inline void UsrpConfig::set_rx_gains(int index, double value) {
  _internal_mutable_rx_gains()->Set(index, value);
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.rx_gains)
}
inline void UsrpConfig::add_rx_gains(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_rx_gains()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.rx_gains)
}
inline const ::google::protobuf::RepeatedField<double>& UsrpConfig::rx_gains() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.rx_gains)
  return _internal_rx_gains();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL UsrpConfig::mutable_rx_gains()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.rx_gains)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rx_gains();
}
inline const ::google::protobuf::RepeatedField<double>&
UsrpConfig::_internal_rx_gains() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_gains_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_rx_gains() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rx_gains_;
}

// repeated string tx_ants = 14;
inline int UsrpConfig::_internal_tx_ants_size() const {
  return _internal_tx_ants().size();
}
inline int UsrpConfig::tx_ants_size() const {
  return _internal_tx_ants_size();
}
inline void UsrpConfig::clear_tx_ants() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_ants_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::add_tx_ants()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_tx_ants()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_add_mutable:usrp_proto.UsrpConfig.tx_ants)
  return _s;
}
inline const ::std::string& UsrpConfig::tx_ants(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.tx_ants)
  return _internal_tx_ants().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::mutable_tx_ants(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:usrp_proto.UsrpConfig.tx_ants)
  return _internal_mutable_tx_ants()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::set_tx_ants(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_tx_ants()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.tx_ants)
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::add_tx_ants(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_tx_ants(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.tx_ants)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& UsrpConfig::tx_ants()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.tx_ants)
  return _internal_tx_ants();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::mutable_tx_ants() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.tx_ants)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tx_ants();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
UsrpConfig::_internal_tx_ants() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_ants_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_tx_ants() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tx_ants_;
}

// repeated string rx_ants = 15;
inline int UsrpConfig::_internal_rx_ants_size() const {
  return _internal_rx_ants().size();
}
inline int UsrpConfig::rx_ants_size() const {
  return _internal_rx_ants_size();
}
inline void UsrpConfig::clear_rx_ants() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_ants_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::add_rx_ants()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_rx_ants()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_add_mutable:usrp_proto.UsrpConfig.rx_ants)
  return _s;
}
inline const ::std::string& UsrpConfig::rx_ants(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.rx_ants)
  return _internal_rx_ants().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::mutable_rx_ants(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:usrp_proto.UsrpConfig.rx_ants)
  return _internal_mutable_rx_ants()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::set_rx_ants(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_rx_ants()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.rx_ants)
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::add_rx_ants(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_rx_ants(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.rx_ants)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& UsrpConfig::rx_ants()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.rx_ants)
  return _internal_rx_ants();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::mutable_rx_ants() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.rx_ants)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rx_ants();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
UsrpConfig::_internal_rx_ants() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_ants_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_rx_ants() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rx_ants_;
}

// repeated string tx_files = 16;
inline int UsrpConfig::_internal_tx_files_size() const {
  return _internal_tx_files().size();
}
inline int UsrpConfig::tx_files_size() const {
  return _internal_tx_files_size();
}
inline void UsrpConfig::clear_tx_files() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_files_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::add_tx_files()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_tx_files()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_add_mutable:usrp_proto.UsrpConfig.tx_files)
  return _s;
}
inline const ::std::string& UsrpConfig::tx_files(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.tx_files)
  return _internal_tx_files().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::mutable_tx_files(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:usrp_proto.UsrpConfig.tx_files)
  return _internal_mutable_tx_files()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::set_tx_files(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_tx_files()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.tx_files)
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::add_tx_files(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_tx_files(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.tx_files)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& UsrpConfig::tx_files()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.tx_files)
  return _internal_tx_files();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::mutable_tx_files() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.tx_files)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tx_files();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
UsrpConfig::_internal_tx_files() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_files_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_tx_files() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tx_files_;
}

// repeated string rx_files = 17;
inline int UsrpConfig::_internal_rx_files_size() const {
  return _internal_rx_files().size();
}
inline int UsrpConfig::rx_files_size() const {
  return _internal_rx_files_size();
}
inline void UsrpConfig::clear_rx_files() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_files_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000800U);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::add_rx_files()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_rx_files()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_add_mutable:usrp_proto.UsrpConfig.rx_files)
  return _s;
}
inline const ::std::string& UsrpConfig::rx_files(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.UsrpConfig.rx_files)
  return _internal_rx_files().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL UsrpConfig::mutable_rx_files(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:usrp_proto.UsrpConfig.rx_files)
  return _internal_mutable_rx_files()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::set_rx_files(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_rx_files()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:usrp_proto.UsrpConfig.rx_files)
}
template <typename Arg_, typename... Args_>
inline void UsrpConfig::add_rx_files(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_rx_files(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_add:usrp_proto.UsrpConfig.rx_files)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& UsrpConfig::rx_files()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:usrp_proto.UsrpConfig.rx_files)
  return _internal_rx_files();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::mutable_rx_files() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_mutable_list:usrp_proto.UsrpConfig.rx_files)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_rx_files();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
UsrpConfig::_internal_rx_files() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_files_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
UsrpConfig::_internal_mutable_rx_files() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.rx_files_;
}

// -------------------------------------------------------------------

// Request

// .usrp_proto.CommandType cmd = 1;
inline void Request::clear_cmd() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::usrp_proto::CommandType Request::cmd() const {
  // @@protoc_insertion_point(field_get:usrp_proto.Request.cmd)
  return _internal_cmd();
}
inline void Request::set_cmd(::usrp_proto::CommandType value) {
  _internal_set_cmd(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:usrp_proto.Request.cmd)
}
inline ::usrp_proto::CommandType Request::_internal_cmd() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::usrp_proto::CommandType>(_impl_.cmd_);
}
inline void Request::_internal_set_cmd(::usrp_proto::CommandType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cmd_ = value;
}

// string tx_shm_name = 2;
inline void Request::clear_tx_shm_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_shm_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Request::tx_shm_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.Request.tx_shm_name)
  return _internal_tx_shm_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Request::set_tx_shm_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.tx_shm_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:usrp_proto.Request.tx_shm_name)
}
inline ::std::string* PROTOBUF_NONNULL Request::mutable_tx_shm_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_tx_shm_name();
  // @@protoc_insertion_point(field_mutable:usrp_proto.Request.tx_shm_name)
  return _s;
}
inline const ::std::string& Request::_internal_tx_shm_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tx_shm_name_.Get();
}
inline void Request::_internal_set_tx_shm_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tx_shm_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Request::_internal_mutable_tx_shm_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.tx_shm_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Request::release_tx_shm_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usrp_proto.Request.tx_shm_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.tx_shm_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.tx_shm_name_.Set("", GetArena());
  }
  return released;
}
inline void Request::set_allocated_tx_shm_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.tx_shm_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.tx_shm_name_.IsDefault()) {
    _impl_.tx_shm_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:usrp_proto.Request.tx_shm_name)
}

// .usrp_proto.UsrpConfig config = 3;
inline bool Request::has_config() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.config_ != nullptr);
  return value;
}
inline void Request::clear_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.config_ != nullptr) _impl_.config_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::usrp_proto::UsrpConfig& Request::_internal_config() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::usrp_proto::UsrpConfig* p = _impl_.config_;
  return p != nullptr ? *p : reinterpret_cast<const ::usrp_proto::UsrpConfig&>(::usrp_proto::_UsrpConfig_default_instance_);
}
inline const ::usrp_proto::UsrpConfig& Request::config() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.Request.config)
  return _internal_config();
}
inline void Request::unsafe_arena_set_allocated_config(
    ::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.config_);
  }
  _impl_.config_ = reinterpret_cast<::usrp_proto::UsrpConfig*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:usrp_proto.Request.config)
}
inline ::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE Request::release_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::usrp_proto::UsrpConfig* released = _impl_.config_;
  _impl_.config_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE Request::unsafe_arena_release_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usrp_proto.Request.config)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::usrp_proto::UsrpConfig* temp = _impl_.config_;
  _impl_.config_ = nullptr;
  return temp;
}
inline ::usrp_proto::UsrpConfig* PROTOBUF_NONNULL Request::_internal_mutable_config() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.config_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::usrp_proto::UsrpConfig>(GetArena());
    _impl_.config_ = reinterpret_cast<::usrp_proto::UsrpConfig*>(p);
  }
  return _impl_.config_;
}
inline ::usrp_proto::UsrpConfig* PROTOBUF_NONNULL Request::mutable_config()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::usrp_proto::UsrpConfig* _msg = _internal_mutable_config();
  // @@protoc_insertion_point(field_mutable:usrp_proto.Request.config)
  return _msg;
}
inline void Request::set_allocated_config(::usrp_proto::UsrpConfig* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.config_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.config_ = reinterpret_cast<::usrp_proto::UsrpConfig*>(value);
  // @@protoc_insertion_point(field_set_allocated:usrp_proto.Request.config)
}

// -------------------------------------------------------------------

// Response

// .usrp_proto.Status status = 1;
inline void Response::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::usrp_proto::Status Response::status() const {
  // @@protoc_insertion_point(field_get:usrp_proto.Response.status)
  return _internal_status();
}
inline void Response::set_status(::usrp_proto::Status value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:usrp_proto.Response.status)
}
inline ::usrp_proto::Status Response::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::usrp_proto::Status>(_impl_.status_);
}
inline void Response::_internal_set_status(::usrp_proto::Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string msg = 2;
inline void Response::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Response::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.Response.msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Response::set_msg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:usrp_proto.Response.msg)
}
inline ::std::string* PROTOBUF_NONNULL Response::mutable_msg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:usrp_proto.Response.msg)
  return _s;
}
inline const ::std::string& Response::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void Response::_internal_set_msg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Response::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Response::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usrp_proto.Response.msg)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.msg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.msg_.Set("", GetArena());
  }
  return released;
}
inline void Response::set_allocated_msg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:usrp_proto.Response.msg)
}

// string rx_shm_name = 3;
inline void Response::clear_rx_shm_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_shm_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Response::rx_shm_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:usrp_proto.Response.rx_shm_name)
  return _internal_rx_shm_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Response::set_rx_shm_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.rx_shm_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:usrp_proto.Response.rx_shm_name)
}
inline ::std::string* PROTOBUF_NONNULL Response::mutable_rx_shm_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_rx_shm_name();
  // @@protoc_insertion_point(field_mutable:usrp_proto.Response.rx_shm_name)
  return _s;
}
inline const ::std::string& Response::_internal_rx_shm_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_shm_name_.Get();
}
inline void Response::_internal_set_rx_shm_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_shm_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Response::_internal_mutable_rx_shm_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.rx_shm_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Response::release_rx_shm_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:usrp_proto.Response.rx_shm_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.rx_shm_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rx_shm_name_.Set("", GetArena());
  }
  return released;
}
inline void Response::set_allocated_rx_shm_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.rx_shm_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rx_shm_name_.IsDefault()) {
    _impl_.rx_shm_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:usrp_proto.Response.rx_shm_name)
}

// uint64 rx_nsamps_per_ch = 4;
inline void Response::clear_rx_nsamps_per_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_nsamps_per_ch_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t Response::rx_nsamps_per_ch() const {
  // @@protoc_insertion_point(field_get:usrp_proto.Response.rx_nsamps_per_ch)
  return _internal_rx_nsamps_per_ch();
}
inline void Response::set_rx_nsamps_per_ch(::uint64_t value) {
  _internal_set_rx_nsamps_per_ch(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:usrp_proto.Response.rx_nsamps_per_ch)
}
inline ::uint64_t Response::_internal_rx_nsamps_per_ch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rx_nsamps_per_ch_;
}
inline void Response::_internal_set_rx_nsamps_per_ch(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rx_nsamps_per_ch_ = value;
}

// uint32 num_rx_ch = 5;
inline void Response::clear_num_rx_ch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_rx_ch_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t Response::num_rx_ch() const {
  // @@protoc_insertion_point(field_get:usrp_proto.Response.num_rx_ch)
  return _internal_num_rx_ch();
}
inline void Response::set_num_rx_ch(::uint32_t value) {
  _internal_set_num_rx_ch(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:usrp_proto.Response.num_rx_ch)
}
inline ::uint32_t Response::_internal_num_rx_ch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.num_rx_ch_;
}
inline void Response::_internal_set_num_rx_ch(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.num_rx_ch_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace usrp_proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::usrp_proto::CommandType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::usrp_proto::CommandType>() {
  return ::usrp_proto::CommandType_descriptor();
}
template <>
struct is_proto_enum<::usrp_proto::Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::usrp_proto::Status>() {
  return ::usrp_proto::Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // usrp_5fprotocol_2eproto_2epb_2eh
